export const Login = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  ACCESSTOKEN: "ACCESSTOKEN",
};

export const photos = {
  PHOTOS_LIST_REQUEST: "PHOTOS_LIST_REQUEST",
  PHOTOS_LIST_REQUEST_SUCCESS: "PHOTOS_LIST_REQUEST_SUCCESS",
  PHOTOS_LIST_REQUEST_FAILURE: "PHOTOS_LIST_REQUEST_FAILURE",
};